### ISSUE TITLE
isOn Property Sets Incorrect State

### ISSUE THREAD

**Issue by burkeholland** [JunichiT/JTMaterialSwitch#1]
It looks like the `isOn` property turns the colors off on the switch, but the switch is still in the "on" position...

![image](https://cloud.githubusercontent.com/assets/686963/11485323/4574d93e-9778-11e5-9959-3ccc781d00a2.png)

**Comment by JunichiT** [comment]
Hi, burkeholland,

Thank you for your reporting!
Could you tell me more details about this so as I can simulate this situation?

**Comment by burkeholland** [comment]
1. Initialize a new JTMaterialSwitch `[[JTMaterialSwitch alloc] init];`
2. Set the `isOn` property to `NO`
3. Add switch to the view
4. Observe that the switch is in between On and Off modes as the Switch colors are off, but the switch position is on as displayed in the screenshot above

**Comment by JunichiT** [comment]
Thanks for describing the detail. I checked this bug on my environment as well, and I've found the point to be revised.

I will update the fixed version soon:)

Thanks,

**Comment by burkeholland** [comment]
Awesome! Thanks so much for looking into it and creating the component in
the first place! Looks great and great work.

**Comment by JunichiT** [comment]
Thanks for your reporting:)
Now this library has been updated to the version 1.1 with the fix of this issue!
