### ISSUE TITLE
isBounceEnabled property has no effect

### ISSUE THREAD

**Issue by burkeholland** [JunichiT/JTMaterialSwitch#2]
It appears that the `isBouncEnabled` property has no affect on the control.
1. Initialize a new JTMaterialSwitch `[[JTMaterialSwitch alloc] init];`
2. Set the `isBounceEnabled` property to `NO`
3. Add switch to the view
4. Observe that the switch still "bounces" when transitioning between on and off states

**Comment by JunichiT** [comment]
Hi, burkeholland

I tried following code as you commented.

```
  JTMaterialSwitch *sw = [[JTMaterialSwitch alloc] init];
  sw.isBounceEnabled = NO;
  sw.center = CGPointMake(300, 70);
  [self.view addSubview:sw];
```

Then it seems `isBounceEnabled` property works properly, like an image below.

![issue](https://cloud.githubusercontent.com/assets/6250288/11609021/564f37e2-9bbd-11e5-9b3a-e758fd8fc04f.gif)

Indeed, there is a little difference of `isBounceEnabled` appearance between `YES` and `NO` .

But if you still have the problem in other condition, please let me know.

Thanks,

**Comment by burkeholland** [comment]
Yikes. That's roughly identical to mine save for the fact that I'm not
setting the center point. Let me go back and see what I'm doing wrong.
Sorry for the false positive!
